

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+08:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

DROP DATABASE IF EXISTS `client`;
CREATE DATABASE `client`;
USE `client`;
DROP TABLE IF EXISTS `client`;
CREATE TABLE `client` (
  `cid` int NOT NULL,
  `name` varchar(120) NOT NULL,
  `env` float DEFAULT NULL,
  `soc` float DEFAULT NULL,
  `gov` float DEFAULT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `client` (`cid`, `name`, `env`, `soc`, `gov`) VALUES
('1', 'John Chia Ming Hai', 48, 30, 22);

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;